MyDjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", include("index.urls")),
    path("user/", include("user.urls")),
]

index/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (IndexTemplate, ProductDetail, ProductList,
                    PublisherBookList, Top10List, login, mydate)

app_name = "index"  # URL namespace
# namespace = 'index'
urlpatterns = [
    path("", IndexTemplate.as_view(), name="index_home"),
    path("list/", ProductList.as_view(), name="index_list"),
    path("<year>/<int:month>/<slug:day>/", mydate, name="mydate"),
    path("<int:pk>/", ProductDetail.as_view(), name="detail"),
    path("login/", login, name="login"),
    path(
        "test/",
        TemplateView.as_view(template_name="index/test2.html"),
        name="test2"),
    path(
        'test3/',
        TemplateView.as_view(template_name='index/test3.html'),
        name='test3'),
    path('top10', Top10List.as_view(), name='top10'),
    path(
        'books/<str:publisher>',
        PublisherBookList.as_view(),
        name='book_publisher')
]

user/urls.py
from django.urls import path

from .views import login2, logout, register, set_password

app_name = "user"  # namespace
urlpatterns = [
    path("login/", login2, name="login"),
    path("register/", register, name="register"),
    path("setpassword/", set_password, name="set_password"),
    path("logout/", logout, name="logout"),
]

index/templates/index/book_list.html
{% extends 'base.html' %}

{% block body %}
<ul>
    {%for book in object_list%}

    <li>
        <a href="{% url 'index:detail' book.pk %}">{{book.name}}
            <span>({{book.authors__count}})</span>
        </a>

    </li>
    {%endfor%}
</ul>

{% endblock body %}

index/templates/index/detail.html
<h2> Book name: {{book.name}}</h1>
    <h3>Publisher: {{book.publisher}}</h3>
    <h3>Pages: {{book.pages}}</h3>
    <h3>Price: {{book.price}}</h3>
    <h3>Rating: {{book.rating}}</h3>
    <h3>Pubdate: {{book.pubdate}}</h3>
    <h3>Authors:</h3>
    <ul>

        {% for author in authors %}
        <li>
            <h3> {{author.name}}</h3>
        </li>

        {% endfor %}

    </ul>

index/templates/index/index.html
{% extends "base.html" %}


{% block title %}
display this page
{% endblock title %}

{% block body %}
<div class="container ">
    <div class="row">
        <div class="col-sm">
            One of three columns
        </div>
        <div class="col-sm">
            One of three columns
        </div>
        <div class="col-sm">
            One of three columns
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            One of three columns
        </div>
        <div class="col-4">
            One of three columns
        </div>

    </div>

    <div class="row">
        <div class="col-md-auto">
            One of three columns
        </div>
        <div class="col-5">
            One of three columns
        </div>
        <div class="col-6">
            One of three columns
        </div>

    </div>
</div>


<h1> sub template.</h1>
{% if username %}
<li>username: {{username|default:"sinber&rita"}}</li>
<li><a href="{% url 'user:logout' %}">logout</a></li>
{%else%}
<li><a href="{% url 'user:login' %}">Login</a></li>
<li><a href="{% url 'user:register' %}">Register</a></li>

{% endif %}


<button type="submit" class="btn btn-primary">SUBMIT</button>

<button type="submit" class="btn btn-primary">提交</button>


<div class="container">
    <h1>my first bootstrap page </h1>
    <p> some text .</p>
</div>
{% endblock body %}

index/templates/index/login.html
{% extends "base.html" %}



{% block body %}
{% if product.errors %}
<p>数据出错啦，错误信息：{{product.errors}}.</p>
{% else %}
<div class="container">

    <form action="" method="post" role="form">
        {% csrf_token %}



        <table>
            {{product.as_p}}
        </table>
        <!-- <input type="submit" value="Submit"> -->

        <button type="submit" class="btn btn-primary" title="click me"> Submit </button>

    </form>
</div>

{% endif %}


{% endblock body %}

index/templates/index/main.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>

<body>
    <div id="header">
        <div class="left" align="center"> WYU</div>
        <div class="center"><a href="http://baidu.com" target="_blank">University</a></div>
        <div class="right">Search</div>
    </div>

    <div id="nav"></div>
    <div id="main">
        <div id="content">
            <div id="left">example</div>
        </div>
    </div>
    <button onclick="javascript:alert('hello javascript')">Click me</button>"
</body>

</html>

index/templates/index/publisher_list.html
{% extends 'base.html' %}


{% block title %}
top10
{% endblock title %}

{% block body %}
<ul>
    {%for publisher in object_list%}
    <li>
        <h3>{{publisher.name}}</h3>
        <ul>

            {% with publisher.top_ten_books as books %}
            {% for book in books %}
            <li> <a href="{% url 'index:detail' book.pk %}">{{book.name}}({{book.rating}})</a></li>
            {% endfor %}
            {% endwith %}


        </ul>
        </a>
    </li>
    {%endfor%}
</ul>
{% endblock body %}

index/templates/index/test.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"><!-- to browser-->
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" media="screen" href="my.css" />
    <link rel="icon" type="image/x-icon" href="../../../static/favicon.ico">
    <script src="main.js"></script>
    <!--to serach engine-->
    <meta name="author" content="www.xxx.com">
    <meta name="keywords" content="django,web,html5">
    <meta name="description" content="this is my first web example.">


</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                One of three columns
            </div>
            <div class="col-sm">
                One of three columns
            </div>
            <div class="col-sm">
                One of three columns
            </div>
        </div>
    </div>

    <button onclick="!function(){
        var list = document.getElementById('list')
        
        alert(list.innerText)
        }()">Click
        me</button>
    <button onclick="open_window()">openwindows</button>

    <a name="top"></a>
    <header>web theme</header>

    <hr />

    <form action="" method="POST">
        Input:
        <input type="text" list="list">
        <datalist id="list">
            <option>123</option>
            <option>abc</option>
            <option>456</option>
            <option>dfe</option>
        </datalist>

    </form>
    <nav>menu</nav>
    <article>main
        <section>
            <a name="middle"></a>
            <h1 class="first">first, you are a student, yes or no. this is one box exaple.</h1>
            <p>one pragraph one</p>
            <p>second pragraph<br /> second</p>
        </section>
        <section>
            <h1>second</h1>
            <pre>
                *
            ***********
                ***
            </pre>
        </section>
    </article>
    <aside>left side</aside>
    <hr />
    <footer>foot</footer>


    <div id="list">

        <ol type="1" start="5">
            <li>one</li>
            <li>two</li>
            <li><a href="http://www.baidu.com" target="_blank">Ok</a>three</li>
            <li><a href="http://www.baidu.com" target="_blank"><img src="../../../static/favicon.ico" title="icon"></a><img
                    src="../../../static/favicon.ico" title="icon"></li><!-- note. -->
        </ol>
    </div>
    <ul>
        <li>first</li>
        <li>second</li>
        <li>third</li>
    </ul>
    <dl>
        <dt>list title</dt>
        <dd>first</dd>
        <dd>se<div style="width: 100px;height:100px; background-color: blue;">one div</div>

            <div style="width: 200px;height:100px;background-color:red;"> another div</div>
            cond
        </dd>
        <dd>third</dd>
    </dl>
    <a href="#top" target="_self">back top</a>
    <a href="#middle" target="_self">back middle</a><br />
    <pre><code>def ok():
print("this is one note.")
    </code></pre>


    <form action="" method="POST" enctype="multipart/form-data">
        <input name="user" type="text" placeholder="please input">
        <input type="password" name="password" placeholder="input password">
        <!-- <br /> -->
        <input type="radio" name="sex" checked="checked" value="male">male
        <input type="radio" name="sex" value="female">female

        <input type="radio" name="sex" value=100>100-age
        <input type="radio" name="sex" value=99>99-age
        <hr />
        <input type="checkbox" name="status" value="on" checked="checked">on
        <input type="checkbox" name="status" value="off">off
        <input type="checkbox" name="status" value="yes">yes



        <input type="reset">
        <input type="button" value="click me" onclick="alert('this is one button')">
    </form>
    <form action="" method="POST" enctype="multipart/form-data">
        choose file <input type="file">
        <input type="submit" value="submit">
    </form>
    <br />
    <br />
    <table style="border:1;width:200px;height:300px;background-color:red;" align="center">
        <tr>
            <th>no.</th>
            <th>&nbsp; name</th>
            <th>age</th>
        </tr>
        <tr>
            <td>1</td>
            <td>sinber</td>
            <td>100</td>
        </tr>
        <tr>
            <td>2</td>
            <td>rita</td>
            <td>99</td>
        </tr>
    </table>

    <script type="text/javascript">
        function hello() {
            var msg = "hello django"
            alert(window.screen.width)

            console.log(msg)
        }

        function open_window() {
            window.open('http://www.baidu.com', 'height=700px, width=1000px, top=200px,left=300px')
        }

        function yes() {
            alert("hijack.")
        }

    </script>
    <button id="yes" class="btn btn-primary " onclick="yes()">Yes</button>
    <script type="text/javascript">
        // var btn = document.getElementById('yes')
        // btn.onclick = function () {
        //     alert("clicj me .")
        // }
    </script>
</body>

</html>

index/templates/index/test2.html
{% extends 'base.html' %}
{% load static %}
<!-- 
{% block head %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/css/bootstrap.min.css">
<script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
<style>
    /* Make the image fully responsive */
    .carousel-inner img {
        width: 100%;
        height: 100%;
    }
</style>
{% endblock head %} -->



{% block body %}

<div class="container-fluid bg">

    <div class="row">
        <div class="col-sm-2" style="background-color:rgb(69, 69, 92)">
        </div>


        <div class="col-sm-8 ">
            <div class=" justify-content-end">
                <ul class="pagination pagination-sm ">
                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>

                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                    打开模态框
                </button>

                <!-- 模态框 -->
                <div class="modal fade" id="myModal">
                    <div class="modal-dialog">
                        <div class="modal-content">

                            <!-- 模态框头部 -->
                            <div class="modal-header">
                                <h4 class="modal-title">模态框头部</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>

                            <!-- 模态框主体 -->
                            <div class="modal-body">
                                模态框内容..
                            </div>

                            <!-- 模态框底部 -->
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div id="demo" class="carousel slide" data-ride="carousel">

                <!-- 指示符 -->
                <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                    <li data-target="#demo" data-slide-to="1"></li>
                    <li data-target="#demo" data-slide-to="2"></li>
                </ul>

                <!-- 轮播图片 -->
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'img/libg1.jpg' %} ">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/libg2.jpg' %}">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/libg3.jpg' %}">
                    </div>
                </div>

                <!-- 左右切换按钮 -->
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>

            </div>

            <div class="col-md-12">
                <div id="card-972068">
                    <div class="card">
                        <div class="card-header">
                            <a class="card-link collapsed" data-toggle="collapse" data-parent="#card-972068" href="#card-element-706213">Collapsible
                                Group Item #1</a>
                        </div>
                        <div id="card-element-706213" class="collapse">
                            <div class="card-body">
                                Anim pariatur cliche...<br />
                                Anim pariatur cliche...<br />
                                Anim pariatur cliche...<br />
                                Anim pariatur cliche...<br />
                                Anim pariatur cliche...<br />
                                Anim pariatur cliche...
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">
                            <a class="collapsed card-link" data-toggle="collapse" data-parent="#card-972068" href="#card-element-454778">Collapsible
                                Group Item #2</a>
                        </div>
                        <div id="card-element-454778" class="collapse">
                            <div class="card-body">
                                Anim pariatur cliche...
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="alert alert-danger"><strong>information! <a href="http://www.baidu.com" target="_blank">start</a></strong></div>
            <div class="alert alert-light alert-dismissable">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>浅灰色!</strong>浅灰色提示框。
            </div>
            <div>
                <button type="button" class="btn btn-warning" onclick="alert('hello click me')">click me</button>
                <a href="http://www.baidu.com" target="_blank" class="btn btn-danger">hyper link</a>
                <input type="text" class="btn btn-light" name="user" value="input username">
            </div>
            <div class="btn-group-vertical">
                <button type="button" class="btn btn-dark">one click</button>
                <button type="button" class="btn btn-light">tow button</button>
                <button type="button" class="btn btn-secondary">three press</button>
                <a href="http://www.baidu.com" target="_blank" class="btn btn-danger">authoer</a>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Sony</button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Tablet</a>
                        <a class="dropdown-item" href="#">Smartphone</a>
                    </div>
                </div>
            </div>
            <div>
                <p>this is one <span class="badge badge-pill badge-primary">default</span>note.</p>
            </div>
            <div class="progress">
                <div class="progress-bar" style="width:40%"></div>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-primary">Apple</button>
                <button type="button" class="btn btn-primary">Samsung</button>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        Sony
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Tablet</a>
                        <a class="dropdown-item" href="#">Smartphone</a>
                    </div>
                </div>
            </div>

            <div>
                <a href="#" data-toggle="tooltip" title="我是提示内容!">鼠标移动到我这</a>
                <a href="#" data-toggle="popover" title="弹出框标题" data-content="弹出框内容">多次点我</a>
                <script>
                    $(document).ready(function () {
                        $('[data-toggle="popover"]').popover();
                    });
                </script>
                <form>
                    <h2>Sign in book system.</h2>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="Enter email">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Password:</label>
                        <input type="password" class="form-control" name="pwd" id="pwd" placeholder="Enter password">
                    </div>
                    <div class="form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" type="checkbox"> Remember me
                        </label>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>

        </div>




        <div class="col-sm-2 text-right " style="background-color:rgb(69, 69, 92)">
        </div>

    </div>

    <div class="row " style="background-color:rgb(56, 69, 70)">
        <div class="col-sm-12 text-center">
            <hr />
            <p class="text-white">&copy;Copyright WYU Lib. 2018</p>
        </div>
    </div>
</div>
<script type="text/javascript">
    function hello() {
        alert("hello")
    }

</script>
{% endblock body %}

index/templates/index/test3.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap TEST</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- 新 Bootstrap4 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/css/bootstrap.min.css">

    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>

    <!-- popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>

    <!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <style>
        .bg {
            background: url('/static/img/libg.jpg');
            background-size: contain;
        }
        /* .jumbotron{
        color:#ccc;
        background-image: url('/static/img/timg.jpg');
        } */
    </style>
</head>

<body>

    <div class="container-fluid" style="background-color:#e9ecef; margin-bottom: 0">
        <div class="row">
            <div class="col-sm-4 " style="padding-top:1%">

                <p class="text-center"> <img src="{% static 'img/logo.png' %}"></p>
            </div>
            <div class="col-sm-4 text-center">

                <h1>五邑大学图书馆</h1>
                <p>这是副标题</p>
            </div>
            <div class="col-sm-4"></div>

        </div>

    </div>


    <nav class="navbar navbar-expand-sm bg-dark navbar-dark ">
        <a class="navbar-brand offset-sm-1" href="#">主页</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">图书</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">馆藏</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">关于</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container" style="margin-top:30px">
        <div class="row">
            <div class="col-sm-4">
                <h2>关于我</h2>
                <h5>我的照片:</h5>
                <div class="fakeimg">这边插入图像</div>
                <p>关于我的介绍..</p>
                <h3>一些链接</h3>
                <p>说明文本</p>
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">激活状态</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">链接</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">链接</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">禁用</a>
                    </li>
                </ul>
                <hr class="d-sm-none">
            </div>
            <div class="col-sm-8">
                <h2>标题</h2>
                <h5>副标题</h5>
                <div class="fakeimg">图像</div>
                <p>一些文本..</p>
                <p>菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！</p>
                <br>
                <h2>标题</h2>
                <h5>副标题</h5>
                <div class="fakeimg">图像</div>
                <p>一些文本..</p>
                <p>菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！菜鸟教程，学的不仅是技术，更是梦想！！！</p>
            </div>
        </div>
    </div>


    <div class=" text-center bg-dark text-white">
        <div class="text-center" style="padding-top:5px; padding-bottom:1%;">

            <p><a href="#">网站地图</a><a href="#">|版权公告</a><a href="#">|联系方式</a></p>
            <p style=" margin-bottom:0px;"><small>&copy;2007-2012 五邑大学图书馆版权所有 技术支持：信息技术与咨询部 电话：6617
                    Email：hlh@wyu.edu.cn</small></p>
            <p style=" margin-bottom:0px;">
                <small> 地址：中国广东江门迎宾大道中99号 邮编：529020 电话：0750-3296612 Email：tsggh@mail.wyu.edu.cn
                </small></p>

        </div>
    </div>
</body>

</html>